name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag in format v1.2.3'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Validate tag
        run: |
          TAG="${{ github.event.inputs.tag }}"

          if ! echo "$TAG" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Tag must be in format v1.2.3"
            exit 1
          fi

      - name: Update package.json
        run: |
          TAG="${{ github.event.inputs.tag }}"
          PACKAGE_VERSION="${TAG#v}"

          pnpm version "$PACKAGE_VERSION" --no-git-tag-version

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add package.json pnpm-lock.yaml
          git commit -m "chore: release ${{ github.event.inputs.tag }}"

      - name: Create tag
        run: |
          git tag "${{ github.event.inputs.tag }}"

      - name: Push commit and tag
        run: |
          git push origin ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.inputs.tag }}
          generate_release_notes: true

  publish:
    uses: ./.github/workflows/publish.yaml
    needs: release
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
